# Generated by Django 4.0.4 on 2022-05-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='liked_articles',
            field=models.ManyToManyField(to='articles.article'),
        ),
    ]
