# Generated by Django 4.0.4 on 2022-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
        ('accounts', '0002_useraccount_liked_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='liked_articles',
            field=models.ManyToManyField(related_name='likes', to='articles.article'),
        ),
    ]
